### ISSUE TITLE
Including ember-data

### ISSUE THREAD

**Issue by RSSchermer** [fernandogmar/Emberjs-RequireJS#1]
I've been playing around a bit with your starterkit and it seems to be working very nicely. I was wondering if you ever tried to use ember-data with it though. I can't seem to get it to work, keep getting the following error: LoadedState.createWithMixins is not a function.

Edit: turns out that I was using a newer version ember-data with an older version of ember (the one on their homepage is not actually up to date). Getting the latest version of ember fixed the issue.

**Comment by fernandogmar** [comment]
Not yet, but I'll try soon ;)

Although I base this starter kit in the Emberjs starter kit, it would be great to have an example using ember-data.  Feel free to share the example, even a pull request ;) .

Happy New Year!

**Comment by FilmKnurd** [comment]
@Rolus What version of Ember and Ember-Data did you use?  I'm also trying to use ember-data with Require, but if I register an adapter:

```
define(function(require) {
  require('ember-data');

  var Store = DS.Store.extend({
    revision: 11,
    adapter: 'DS.FixtureAdapter'
  });

  Store.registerAdapter('App.Help', DS.RESTAdapter.extend({
    url: '/internal/api/v1'
  }));

  DS.RESTAdapter.configure("plurals", {
    help: "help"
  });

  return Store;
});
```

My app, which worked with fixtures, now produces the errors:

```
Error while loading route: Error {} ember.js:339
Uncaught Error: assertion failed: Your model must not be anonymous. It was (subclass of DS.Model) ember.js:52
```

**Comment by FilmKnurd** [comment]
Ah! I found my problem.  In main.js I was using:

```
window.App = Ember.Application.create(AppConfig);
```

But I needed to use Applicaiton.createWithMixins(AppConfig).

My working main.js

```
(function(root){
  require(["config"], function(config){
    requirejs.config(config);
    require(["App", "ember", "ember-data"], function(AppConfig, Ember, DS){

      window.App = Ember.Application.createWithMixins(AppConfig);

    });
  });
})(this);
```
