### ISSUE TITLE
create new Tab problem

### ISSUE THREAD

**Issue by business-software** [fernandogmar/Emberjs-RequireJS#7]
thanks for great working on this,my question is I want to use yout createTab function in tabListController
when I pass the input value from TabCreationView to tabListController

var TabCreationView = Em.View.extend({
    content: null,
  controller: tabListController,
    template: Ember.Handlebars.compile(tabCreationTemplate),
    createTab: function() {
    var new_name = this.$("input").val();
   var controller = this.get("controller");  
    controller.createTab(new_name);
    },
});

but the createTab function just grab the string (problem is not the object) to addTab function so I just get a empty tab there.

```
createTab: function(name) {

    var tab = TabModel.create(name);
    this.addTab(tab);
    this.showTab(tab);

},
```

Is there any way to make it?

**Comment by fernandogmar** [comment]
Sorry,

it is my fault, I extracted this example for a bigger project I was working on.

First createTab of tabListController has to change to this:

``` javascript
createTab: function(properties){
        var tab = TabModel.create(properties);

        this.addTab(tab);
        this.showTab(tab);
    }
```

and if you se the tabFixtures.js in the example, the properties of a tab are:

``` javascript
var tab_properties = {
    order: 1,
    name: "First Tab",
    html: "<h1>First Tab Content</h1><p>This is the first tab content.</p>"
  };
```

so in order to create a new tab in the example

``` javascript
tabListController.createTab({
    order: 1,
    name: "First Tab",
    html: "<h1>First Tab Content</h1><p>This is the first tab content.</p>"
  });
```

But you can change this properties if you change the templates
for example selectedTabTemplate.html if you want to show other properties or whatever you want...

I hope this helps you

Have fun!

**Comment by business-software** [comment]
Thanks for great feedback, that help me a lot and work fine for me,
yesterday I got other solution for it ,kindof similar to your solution, but I just use addTab instead of TabModel.create(properties) ,and working fine for me as well

in tabListController
        createTab: function(string) {

```
        this.addTab({
            order: 4,
            name: string,
            html: '<h1>'+new_name+'</h1>',
        });
        this.showTab(tab);
    },
```

in TabCreationView

   createTab: function() {
            var new_name = this.$("#input").val();
            var controller = this.get("controller");
            controller.createTab(new_name);
            $("#input").val('');
        },

because this method just call  TabModel.create here
 addTab: function(tab) {

```
        var tabs = this.get('content');
        if (!tab.get) {
            tab = TabModel.create(tab);
        }
        tabs.pushObject(tab);

        return this;
    },
```

cheers
