### ISSUE TITLE
grab json object from server

### ISSUE THREAD

**Issue by business-software** [fernandogmar/Emberjs-RequireJS#8]
If I want to to grab json object from server instead of hard coding in the tabFixtures. Is there any better way to achieve that? must I use RESTAdapter? any change I still make for this structure?

sorry for so many questions, because I am totally new to this ember .

cheers

**Comment by fernandogmar** [comment]
In that case you have many options, 

you can use Data by emberjs team: https://github.com/emberjs/data

or you can use other alternatives as JQuery.ajax http://api.jquery.com/jQuery.ajax/ . At this moment jquery is included in the starter kit of this repository

Good luck! ;)
