### ISSUE TITLE
Ember cannot find Handlebars

### ISSUE THREAD

**Issue by knownasilya** [fernandogmar/Emberjs-RequireJS#9]
I'm getting this error: 

> Ember Handlebars requires Handlebars 1.0.0-rc.3 or greater. Include a SCRIPT tag in the HTML HEAD linking to the Handlebars file before you link to Ember. 

I have `handlebars` declared in my require paths, and the version is `rc.4`, so it is greater.

My `ember` shim looks like this:

```
ember: {
  deps: ["jquery", "handlebars"],
  exports: "Ember"
}
```

Not sure what the issue is..

**Comment by knownasilya** [comment]
Looks like it was an Ember bug. See https://github.com/emberjs/ember.js/issues/2288

**Comment by fernandogmar** [comment]
You are right ;), compatibility issue...??

`Ember 1.0.0-rc.3`:

```
Ember.assert("Ember Handlebars requires Handlebars 1.0.0-rc.3 or greater. Include a SCRIPT tag in the HTML HEAD linking to the Handlebars file before you link to Ember.", Handlebars && Handlebars.COMPILER_REVISION === 2);
```

`Handlebars  1.0.0-rc.4`:

```
Handlebars.VERSION = "1.0.0-rc.4";
Handlebars.COMPILER_REVISION = 3;
```
